import type { KeyFunctionMap } from '../interface'

export const DefaultArcadeModeKeyMap: KeyFunctionMap = {
  thrust: { activators: ['w', 'ArrowUp'], keyStatus: false, displayText: 'Thrust' },
  reverseThrust: { activators: ['s', 'ArrowDown'], keyStatus: false, displayText: 'Reverse Thrust' },
  boost: { activators: ['b'], keyStatus: false, displayText: 'Boost' },
  halt: { activators: ['h'], keyStatus: false, toggle: true, displayText: 'Halt' },
  turnLeft: { activators: ['a', 'ArrowLeft'], keyStatus: false, displayText: 'Turn Left' },
  turnRight: { activators: ['d', 'ArrowRight'], keyStatus: false, displayText: 'Turn Right' },
  strafeLeft: { activators: ['q', 'PageUp'], keyStatus: false, displayText: 'Strafe Left' },
  strafeRight: { activators: ['e', 'PageDown'], keyStatus: false, displayText: 'Strafe Right' },
  fire: { activators: ['ctrl'], keyStatus: false, displayText: 'Fire' },
  reload: { activators: ['r'], keyStatus: false, displayText: 'Reload' },
  selfDestroy: { activators: ['k'], keyStatus: false, displayText: 'Self Destroy' },
  systemGraphs: { activators: ['g'], keyStatus: false, toggle: true, displayText: 'System Graphs' },
  leaderBoard: {
    activators: ['p'],
    keyStatus: false,
    store: false,
    toggle: true,
    displayText: 'Leader Board',
  },
  hotKeys: {
    activators: ['o'],
    keyStatus: false,
    store: false,
    toggle: true,
    displayText: 'Hot Keys',
  },
  shipSettings: {
    activators: ['i'],
    keyStatus: false,
    store: false,
    toggle: true,
    displayText: 'Ship Settings',
  },
  shipDetails: {
    activators: ['y'],
    keyStatus: false,
    store: false,
    toggle: true,
    displayText: 'Ship Details',
  },
  chat: {
    activators: ['c'],
    keyStatus: false,
    store: false,
    toggle: true,
    displayText: 'Chat',
  },
  menu: {
    activators: ['Escape'],
    keyStatus: false,
    store: false,
    toggle: true,
    displayText: 'Menu',
  },
  jump: {
    activators: [' '],
    keyStatus: false,
    store: false,
    toggle: false,
    displayText: 'Jump',
  },
  changeMode: {
    activators: ['m'],
    keyStatus: false,
    store: false,
    toggle: false,
    displayText: 'Change Mode',
  },
  tractorBeam: {
    activators: ['t'],
    keyStatus: false,
    store: false,
    toggle: true,
    displayText: 'Tractor Beam',
  },
  healthBar: {
    activators: ['l'],
    keyStatus: false,
    store: false,
    toggle: true,
    displayText: 'Healthbar',
  },
  name: 'Arcade',
}
